modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
credits="Thanks to all the media that inspired the content in this modification, especially Pokemon." #optional
authors="SpikybumJolteon" #optional

[[mods]] #mandatory
modId="kindredlegacy" #mandatory
version="1.3.0.10" #mandatory
displayName="Kindred Legacy" #mandatory
description='''
This is a mod that takes inspiration
from various popular media to create
a new adventure, using Pokemon as
its core base.
'''

[[dependencies.kindredlegacy]] #optional
	modId="forge" #mandatory
	mandatory=true #mandatory
	versionRange="[31,)" #mandatory
	ordering="NONE"
	side="BOTH"
# Here's another dependency
[[dependencies.kindredlegacy]] #optional
	modId="minecraft"
	mandatory=true
	versionRange="[1.15.2]"
	ordering="NONE"
	side="BOTH"